### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by Skyridr** [akaminetzkyp/royale-stats#1]
When starting up: python3 main.py CLANIDHERE

Getting:

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.cr-api.com
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    logger.log_donations()
  File "/logger.py", line 79, in log_donations
    self.log_data(path, new_donations, True)
  File "/logger.py", line 58, in log_data
    writer.writerows(data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

**Comment by kaminetzky** [comment]
I pushed a small change. Could you please try to run the script again?

I tested the script in macOS and Raspbian. Are you using Windows?

Thanks!

**Comment by Skyridr** [comment]
Thanks, works now!

Forgot to mention, using Ubuntu Linux 16.04

**Comment by Skyridr** [comment]
Also, small report.

Noticed 2 names in the sheet are being named at weird characters.

"Ã˜Å˜IÎœÎ”ÅÒœÎ”"
"â­ï¸ M1k1 â­ï¸"

Their names ingame are written in symbols though, so it's obvious its being printed like this. But not sure how it can be done in a cleaner way in excel.

**Comment by kaminetzky** [comment]
Interesting problem. I'm currently out of town so I can't check it out in detail. However, I'll be back on Tuesday, where I'll try to fix it immediately.

**Comment by Skyridr** [comment]
Just a small update.

The names above:

Ã˜Å˜IÎœÎ”Å�ÒœÎ
â­�ï¸� M1k1 â­�ï¸�

Should be showing like this:

ØŘIΜΔŁҜΔ
⭐️ M1k1 ⭐️

**Comment by kaminetzky** [comment]
Perfect. Thank you very much for the feedback!

I'll fix it on the weekend.
