### ISSUE TITLE
Python uses a different timezone over system/php time.

### ISSUE THREAD

**Issue by Skyridr** [akaminetzkyp/royale-stats#2]
I noticed that the timestamp the log shows is different time over the system and or the time set on PHP. Anyway that the python can use the system time instead? Otherwise the time stamp is inconsistent with the time I use.

OS: Ubuntu 16.04

Regards,
Skyrider

**Comment by kaminetzky** [comment]
It saves the current UTC. I'll add that to the readme.

If you want I can add an option to log using the system time.

**Comment by Skyridr** [comment]
That would be great! Appreciate it :D
