### ISSUE TITLE
extra Line breaks in CSV file

### ISSUE THREAD

**Issue by thing-in-the-back-of-your-mind** [akaminetzkyp/royale-stats#4]
Python 3.6
Windows 10

The CSV output has extra line breaks in the file. This causes issues if I run it a 2nd time to pull the data. 
----Output:
Day / Week,Tuesday 43

Datetime,2017-10-24 17:56:07

Total,1484
--------------------
It show up as having 2 carriage return and a line feed

**Comment by kaminetzky** [comment]
Hello! I'm really sorry for not answering earlier. I've been really busy.

The `csv` files I get have a newline (`\n`) at the end of every line. 

<img width="366" alt="screen shot 2017-11-09 at 9 08 34 am" src="https://user-images.githubusercontent.com/11022568/32604799-b6d1a370-c52d-11e7-8034-b093390ce216.png">

Where are you seeing two carriage returns and a line feed?

Cheers!

**Comment by thing-in-the-back-of-your-mind** [comment]
Using Notepad++, I see..

![image](https://user-images.githubusercontent.com/33102768/32621772-c0845608-c535-11e7-804a-f6922a2a2db3.png)

I fixed the issues by changing
import csv   to  import unicodecsv as csv

**Comment by kaminetzky** [comment]
Interesting. Thanks for the fix!
