### ISSUE TITLE
[solution] Fix with the latest API changes

### ISSUE THREAD

**Issue by Skyridr** [akaminetzkyp/royale-stats#5]
The author is most likely quite busy and hasn't updated his system in a few weeks, so here's a fix that you can use. I'm not sure if this is the 'proper' solution, but it works.

Change the api_wrapper.py file, with the following:

```python
import requests
import logging

class Wrapper:
    def __init__(self, clan_tag):
        self.url = 'http://api.cr-api.com/clan/' + clan_tag
        self.data = None
        self.headers = {"auth": "xxxxx"}
        r = requests.get(self.url, headers=self.headers)
        data = r.json()
        self.update_data()

    def update_data(self):
        try:
            self.data = requests.get(self.url, headers=self.headers).json()
        except requests.exceptions.RequestException as err:
            logging.error(err)
            self.data = {'error': True, 'message': err}
```

Replace the xxxx (at auth) with the key you've been given on the CR API discord server ( https://discord.gg/nJy93jg ) by using `!crapikey stats` in the #developer-key channel.

Regards,
Skyrider

**Comment by kaminetzky** [comment]
Thank you so much, @Skyrid3r!

**Comment by kaminetzky** [comment]
Hey @Skyrid3r! I have updated the script so it works with the new API. Thank you for your contribution!
